texts = {
    'format': 'us-US',
    'inprogress': 'Inprogress',
    'completed': 'Completed',
    'options': 'Options',
    'view_data': 'View Data',
    'view_progress': 'View Progress',
    'select_user': 'Select User',
    'event_detail': 'Activity Detail',
    'create_date': 'Create Date',
    'progress': 'Progress',
    'hide': '▲ Hide',
    'view': '▼ View',
    'enable': 'Enable',
    'on_hold': 'On Hold',
    'disable': 'Disable',
    'edit': 'Edit',
    'change_password': 'Change Password',
    'delete': 'Delete',
    'referred_job': 'Referred Jobs',
    'time': ' , ',
    'na': '',
    'want_delete': 'Do you want to delete it?',
    'cancel': 'Cancel',
    'position': 'Position',
    'job_category': 'Job Category',
    'employment_type': 'Employment Type',
    'work_day': 'Work Day',
    'work_time': 'Time Work',
    'work_location': 'Work Location',
    'salary': 'Salary',
    'description': 'Description',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'education': 'Educations',
    'experience': 'Experiences',
    'option': 'Options',
    'expect_salary': 'Expect Salary',
    'status': 'Status',
    'level': 'Level',
    'm3': 'Lower Secondary Education',
    'm6': 'Upper Secondary Education',
    'vc': 'Vocational Certificate',
    'hvc': 'Higher Vocational Certificate',
    'bd': "Bachelor's Degree",
    'md': "Master's Degree",
    'dd': "Doctoral Degree",
    'school': 'School',
    'faculty': 'Faculty',
    'major': 'Major',
    'graduation_year': 'Graduation Year',
    'gpa': 'GPA',
    'company_name': 'Company Name',
    'select': 'Select',
    'menu_code': 'Menu Code',
    'menu_name': 'Menu Name',
    'entrepreneur': 'Entrepreneur',
    'company': 'Company',
    'applied_job': 'Applied Job',
    'apply_job': 'Apply Job',
    'want_apply': 'Do you want to apply for this job?',
    'okay': 'Okay',
    'view_detail': 'View',
    'email': 'E-mail',
    'apply_date': 'Apply Date',
    'name': 'Name',
    'gender': 'Gender',
    'tel': 'Phone Number',
    'success': 'SUCCESS',
    'error': 'ERROR',
    'job_application': 'Job Applications',
    'post': 'Post',
    'period': 'Period',
    'posts': 'posts',
    'month': 'months',
    'apply_package': 'Apply Package',
    'start_date': 'Start Date',
    'end_date': 'End Date',
    'remaining_amount': 'Remaining Amount',
    'want_apply_package': 'Do you want to apply for a package?',
    'accept': 'Accept',
    'no_package': 'No Package',
    'copied': 'Copied',
    'packages': 'Packages',
    'exist': 'E-mail already exists',
    'exist_username': 'Username already exists',
    'disable_login': 'This account is disabled or the account does not exist in the system.',
    'unauthorized': 'The username or password is incorrect.',
    'referred_job_user': 'Referred Job',
    'unauthorized_password': 'The old password and the new password do not match.',
    'not_match': 'Password and password confirmation do not match.',
    'more_6': 'Password length must be more than 6 characters.',
    'agreed': 'As agreed',
    'baht': 'Baht',
    'sunday': 'Sunday',
    'monday': 'Monday',
    'tuesday': 'Tuesday',
    'wednesday': 'Wednesday',
    'thursday': 'Thursday',
    'friday': 'Friday',
    'saturday': 'Saturday',
    'change_status': 'Change Status',
    'want_statusflag': 'Do you want to change the status?',

}
