texts = {
    'format': 'us-US',
    'inprogress': 'Inprogress',
    'completed': 'Completed',
    'options': 'Options',
    'view_data': 'View Data',
    'view_progress': 'View Progress',
    'select_user': 'Select User',
    'event_detail': 'Event Detail',
    'create_date': 'Create Date',
    'progress': 'Progress',
    'hide': '▲ Hide',
    'view': '▼ View',
    'enable': 'Enable',
    'on_hold': 'On Hold',
    'disable': 'disable',
    'edit': 'Edit',
    'change_password': 'Change Password',
    'delete': 'Delete',
    'referred_job': 'Referred Jobs',
    'time': ' , ',
    'na': '',
    'want_delete': 'Do you want to delete it?',
    'cancel': 'Cancel',
    'position': 'Position',
    'job_category': 'Job Category',
    'employment_type': 'Employment Type',
    'work_day': 'Work Day',
    'work_time': 'Time Work',
    'work_location': 'Work Location',
    'salary': 'Salary',
    'description': 'Description',
    'male': 'Male',
    'female': 'Female',
    'other': 'Other',
    'education': 'Educations',
    'experience': 'Experiences',
    'option': 'Options',
    'expect_salary': 'Expect Salary',
    'status': 'Status',
    'level': 'Level',
    'm3': 'Lower Secondary Education',
    'm6': 'Upper Secondary Education',
    'vc': 'Vocational Certificate',
    'hvc': 'Higher Vocational Certificate',
    'bd': "Bachelor's Degree",
    'md': "Master's Degree",
    'dd': "Doctoral Degree",
    'school': 'School',
    'faculty': 'Faculty',
    'major': 'Major',
    'graduation_year': 'Graduation Year',
    'gpa': 'GPA',
    'company_name': 'Company Name',

}
