texts = {
  'format': 'th-TH',
  'inprogress': 'กำลังดำเนินการ',
  'completed': 'เสร็จสิ้น',
  'options': 'ตัวเลือก',
  'view_data': 'ดูข้อมูล',
  'view_progress': 'ดูความคืบหน้า',
  'select_user': 'กรุณาเลือกผู้ใช้',
  'event_detail': 'รายละเอียด',
  'create_date': 'วันที่บันทึก',
  'progress': 'ความคืบหน้า',
  'hide': '▲ ซ่อนข้อมูล',
  'view': '▼ ดูข้อมูลเพิ่มเติม',
  'enable': 'เปิดใช้งาน',
  'on_hold': 'รอดำเนินการ',
  'disable': 'ปิดใช้งาน',
  'edit': 'แก้ไข',
  'change_password': 'เปลี่ยนรหัสผ่าน',
  'delete': 'ลบ',
  'referred_job': 'งานที่รับสมัคร',
  'time': ' เวลา ',
  'na': ' น.',
  'want_delete': 'คุณต้องการลบใช่ไหม',
  'cancel': 'ยกเลิก',
  'position': 'ตำแหน่ง',
  'job_category': 'ประเภทงาน',
  'employment_type': 'ประเภทการจ้างงาน',
  'work_day': 'วันทำงาน',
  'work_time': 'เวลาทำงาน',
  'work_location': 'สถานที่ทำงาน',
  'salary': 'เงินเดือน',
  'description': 'รายละเอียด',
  'male': 'ชาย',
  'female': 'หญิง',
  'other': 'อื่นๆ',
  'education': 'ประวัติการศึกษา',
  'experience': 'ประสบการณ์',
  'option': 'ตัวเลือก',
  'expect_salary': 'เงินเดือนที่ต้องการ',
  'status': 'สถานะ',
  'level': 'ระดับการศึกษา',
  'm3': 'มัฐยมศึกษาปีที่ 3',
  'm6': 'มัฐยมศึกษาปีที่ 6',
  'vc': 'ประกาศนียบัตรวิชาชีพ',
  'hvc': 'ประกาศนียบัตรวิชาชีพชั้นสูง',
  'bd': 'ปริญญาตรี',
  'md': 'ปริญญาโท',
  'dd': 'ปริญญาเอก',
  'school': 'สถานศึกษา',
  'faculty': 'คณะ',
  'major': 'สาขา',
  'graduation_year': 'ปีที่สำเร็จการศึกษา',
  'gpa': 'GPA',
  'company_name': 'ชื่อบริษัท',
};
